Fix/w3c compatibility issues
testproject-io/csharp-opensdk pull request #101
Opened 2021-02-09 09:06 UTC by basdijkstra

This PR fixes W3C compatibility issues that caused a number of problems when using, for example, `By.Id` locators and Selenium commands that invoke the `executeScript` WebDriver W3C command.

2021-02-09 19:07 UTC, eldarkra requested changes

2021-02-09 19:07 UTC, eldarkra commented on TestProject.OpenSDK/Drivers/BaseDriver.cs
> +            if (AgentClient.GetInstance().AgentSession.Dialect.Equals("W3C"))
I see that `AgentClient.GetInstance().AgentSession.Dialect.Equals("W3C")` is being used on several occasions. I think that an extension method (something like `AgentClient.IsW3CDialect()`) can be created.

2021-02-09 19:07 UTC, eldarkra commented on TestProject.OpenSDK/Drivers/BaseDriver.cs
> +            if (!AgentClient.GetInstance().AgentSession.Dialect.Equals("W3C") && driverCommandToExecute.ShouldBePatched())
Use the extension method

2021-02-09 19:07 UTC, eldarkra commented on TestProject.OpenSDK/Internal/Helpers/CommandExecutors/CustomHttpCommandExecutor.cs
> +            if (AgentClient.GetInstance().AgentSession.Dialect.Equals("W3C"))
Use the extension method

2021-02-10 08:21 UTC, basdijkstra commented
@eldarkra added and applied the requested extension method, please re-review.

2021-02-10 10:47 UTC, eldarkra approved these changes

2021-02-10 10:48 UTC, eldarkra commented
@basdijkstra looks OK but now the brach is out of date once again.

2021-02-10 10:50 UTC, basdijkstra commented
> @basdijkstra looks OK but now the brach is out of date once again.

No problem, I'll rebase and merge it myself. Thanks.

2021-02-10 10:58 UTC, merged