Allow to control report type - local, cloud or both
testproject-io/csharp-opensdk pull request #157
Opened 2021-03-31 09:03 UTC by Rantzur1992

Added support for control of report generation, which can be loca, cloud or by default, both for supported agent versions.

2021-03-31 23:57 UTC, mstrelex commented
@Rantzur1992 

Why do you have this strange signature instead of your name? `LAPTOP-IB4DPRIG\rantz`

2021-04-01 00:08 UTC, mstrelex requested changes

2021-04-01 00:08 UTC, mstrelex commented on TestProject.OpenSDK/Internal/Rest/AgentClient.cs
> +        /// <throws>AgentConnectionException if the current agent version < <see cref="minLocalReportSupportedVersion"/>.</returns>
A bit confusing formulation, perhaps replacing the `<` sign with `older than` would be better.

2021-04-01 00:08 UTC, mstrelex commented on README.md
> +Via a driver constructor:
Please add a blank line.

2021-04-01 00:08 UTC, mstrelex commented on README.md
> +
What about driver builder?

2021-04-01 00:08 UTC, mstrelex commented on TestProject.OpenSDK/Internal/Rest/Messages/SessionResponses/SessionResponse.cs
> +        public string LocalReport { get; }
And where the path is printed? See https://github.com/testproject-io/java-opensdk/pull/91/commits/85478861e37dd93d0723e6aa720a35d224b33b77#diff-b8310f141bdd5d03ed9a8ea4a6185363318a109e169ec56043b7e92743cffca5R944

2021-04-01 00:17 UTC, mstrelex commented
@Rantzur1992 

Please update HISTORY.md

2021-04-01 06:47 UTC, basdijkstra commented on TestProject.OpenSDK/Internal/Rest/Messages/SessionResponses/SessionResponse.cs
> +        public string LocalReport { get; }
> How does it work when the property in json is camelCase and the C# property is PascalCase?

That's being taken care of here: https://github.com/testproject-io/csharp-opensdk/blob/81c96f4cc1b50de548f564ca23c24a51f36296ce/TestProject.OpenSDK/Internal/Helpers/CustomJsonSerializer.cs#L42. It works for all properties in the `SessionResponse` (and any other Agent response message that should be deserialized into an object).

2021-04-01 06:52 UTC, Rantzur1992 commented on TestProject.OpenSDK/Internal/Rest/Messages/SessionResponses/SessionResponse.cs
> +        public string LocalReport { get; }
Thanks @basdijkstra 
I added a new commit which adds the print to the path of the local report, if applicable.

2021-04-01 06:52 UTC, Rantzur1992 commented on TestProject.OpenSDK/Internal/Rest/AgentClient.cs
> +        /// <throws>AgentConnectionException if the current agent version < <see cref="minLocalReportSupportedVersion"/>.</returns>
Sure, done.

2021-04-01 06:55 UTC, Rantzur1992 commented on README.md
> +Via a driver constructor:
done

2021-04-01 06:56 UTC, Rantzur1992 commented on README.md
> +
DriverBuilder is not implemented in the C# SDK.
I will need to implement it in a separate PR.

2021-04-01 10:08 UTC, Rantzur1992 commented on README.md
> +
@mstrelex PR #158 addresses the creation of DriverBuilder.
After you merge it I will be able to add the DriverType to DriverBuilder.

2021-04-01 16:44 UTC, mstrelex approved these changes

2021-04-01 16:45 UTC, merged