Allow overriding remote connection timeout via driver constructor
testproject-io/csharp-opensdk pull request #204
Opened 2021-06-17 09:13 UTC by s-glatshtein

While investigating https://github.com/testproject-io/csharp-opensdk/issues/170 it was discovered that the command can sometimes timeout, causing it to fail. This is because the default connection timeout was hard-coded to 10 seconds.
This MR does the following:

- Increase default connection timeout to 60 seconds.
- Allow overriding the remote connection timeout via driver constructor

2021-06-17 11:36 UTC, mstrelex requested changes

2021-06-17 11:36 UTC, mstrelex commented on TestProject.OpenSDK/Internal/Helpers/CommandExecutors/CustomHttpCommandExecutor.cs
> +            : this(addressOfRemoteServer, disableReports, TimeSpan.FromSeconds(60))
If there is a default, why specifying it explicitly?

2021-06-20 07:46 UTC, s-glatshtein commented on TestProject.OpenSDK/Internal/Helpers/CommandExecutors/CustomHttpCommandExecutor.cs
> +            : this(addressOfRemoteServer, disableReports, TimeSpan.FromSeconds(60))
The default exists in the driver, not the command executor.
We do not override, nor do we use the default command executors in the SDK

2021-06-20 08:25 UTC, eldarkra commented on TestProject.OpenSDK/Internal/Helpers/CommandExecutors/CustomHttpCommandExecutor.cs
> +            : this(addressOfRemoteServer, disableReports, TimeSpan.FromSeconds(60))
@s-glatshtein , do you "Allow overriding the remote connection timeout via driver constructor"?

2021-06-20 08:30 UTC, s-glatshtein commented on TestProject.OpenSDK/Internal/Helpers/CommandExecutors/CustomHttpCommandExecutor.cs
> +            : this(addressOfRemoteServer, disableReports, TimeSpan.FromSeconds(60))
@eldarkra i do. this is in the 2 separate commits

2021-06-20 08:40 UTC, eldarkra approved these changes

2021-06-20 15:04 UTC, mstrelex approved these changes

2021-06-20 15:04 UTC, merged