Prioritize Development Token Provided in TP_DEV_TOKEN variable over token in constructor
testproject-io/csharp-opensdk pull request #207
Opened 2021-06-20 14:29 UTC by Artem-Kuz

2021-06-20 14:32 UTC, s-glatshtein commented
@eldarkra looks good. can you approve please?

2021-06-23 15:50 UTC, mstrelex approved these changes

2021-06-23 19:05 UTC, mstrelex commented
@s-glatshtein Approved, please rebase and merge.

2021-06-23 20:04 UTC, vitalybu requested changes

2021-06-23 20:04 UTC, vitalybu commented on TestProject.OpenSDK/Internal/Rest/AgentClient.cs
> +                    Logger.Info("Using {0} parameter from environment", this.tpDevToken);
Sensitive data such as a token should not be printed as INFO... Maybe DEBUG.

2021-06-24 12:47 UTC, s-glatshtein commented on TestProject.OpenSDK/Internal/Rest/AgentClient.cs
> +                    Logger.Info("Using {0} parameter from environment", this.tpDevToken);
tpDevToken is the field containing the name of the environment variable.
We should change it to a real constant at some point....

2021-06-24 16:24 UTC, vitalybu approved these changes

2021-06-24 17:20 UTC, merged