Documentation on how to use addon actions via its proxy
testproject-io/csharp-opensdk pull request #220
Opened 2021-07-05 13:36 UTC by Artem-Kuz

Signed-off-by: Artem Kuznetsov <artem.kuznetsov@testproject.io>

2021-07-05 16:12 UTC, mstrelex requested changes

2021-07-05 16:12 UTC, mstrelex commented on README.md
> +Refer to the [Addon Proxy Test](https://github.com/testproject-io/csharp-opensdk/blob/main/TestProject.OpenSDK.Tests/Examples/Addons/ChromeDriverWithAddonTest.cs) for complete example source.
@Artem-Kuz 

This file is missing...

2021-07-05 16:48 UTC, s-glatshtein commented on README.md
> +Refer to the [Addon Proxy Test](https://github.com/testproject-io/csharp-opensdk/blob/main/TestProject.OpenSDK.Tests/Examples/Addons/ChromeDriverWithAddonTest.cs) for complete example source.
@mstrelex it opens for me. It is present in the repo as well

2021-07-05 20:31 UTC, mstrelex commented on README.md
> +Refer to the [Addon Proxy Test](https://github.com/testproject-io/csharp-opensdk/blob/main/TestProject.OpenSDK.Tests/Examples/Addons/ChromeDriverWithAddonTest.cs) for complete example source.
It is indeed now. But the test is not documented and is not reflecting the usage of both element and non-element based actions using proxies, it would be better if the test would be aligned with the Java version - https://github.com/testproject-io/java-opensdk/pull/144/files#diff-b86b1a8e7c6605f33e3868dc150ff84593dfd7dd52e4b418cfc419b3c0194372R72

2021-07-05 20:34 UTC, mstrelex requested changes

2021-07-05 20:34 UTC, mstrelex commented on README.md
> +Refer to the [Addon Proxy Test](https://github.com/testproject-io/csharp-opensdk/blob/main/TestProject.OpenSDK.Tests/Examples/Addons/ChromeDriverWithAddonTest.cs) for complete example source.
@s-glatshtein 

We don't have a proxy generator for C# OpenSDK. \
Why documenting something that can not be used yet?

2021-07-06 06:06 UTC, Artem-Kuz commented on README.md
> +Refer to the [Addon Proxy Test](https://github.com/testproject-io/csharp-opensdk/blob/main/TestProject.OpenSDK.Tests/Examples/Addons/ChromeDriverWithAddonTest.cs) for complete example source.
@mstrelex 
We do support generating addons as dll's in C#, 
then you can include this dll in a test.

2021-07-06 11:36 UTC, closed without merging