fix: added support for XUnit logging
testproject-io/csharp-opensdk pull request #238
Opened 2021-07-28 09:07 UTC by Artem-Kuz

Relates to: #229 
Added XUnitLogger and XUnitLoggerTarget classes which configures the logger output for XUnit.

2021-07-28 09:20 UTC, s-glatshtein commented on README.md
> +TestProject OpenSDK uses NLog API for logging.
Don't think it matters to most people. 
Better remove this sentence and add a title explain this is for output in xUnit tests

2021-07-28 09:20 UTC, s-glatshtein commented on TestProject.OpenSDK/XUnitLogger/XUnitLoggerTarget.cs
> +    public class XunitLoggerTarget : TargetWithLayout
Does it work if the target is internal instead of public?

2021-07-28 09:20 UTC, s-glatshtein commented on TestProject.OpenSDK/XUnitLogger/XUnitLogger.cs
> +﻿// <copyright file="XUnitLogger.cs" company="TestProject">
Should've been 2 commits

2021-07-28 09:20 UTC, s-glatshtein commented on TestProject.OpenSDK/XUnitLogger/XUnitLoggerTarget.cs
> +        /// Writes the log message to console.
to xUnit output helper?

2021-07-28 09:35 UTC, Artem-Kuz commented on TestProject.OpenSDK/XUnitLogger/XUnitLoggerTarget.cs
> +    public class XunitLoggerTarget : TargetWithLayout
Works, and indeed makes sense to make it internal, 
will change

2021-07-28 09:45 UTC, Artem-Kuz commented on TestProject.OpenSDK/XUnitLogger/XUnitLoggerTarget.cs
> +        /// Writes the log message to console.
I made the summary more clear

2021-07-28 09:45 UTC, Artem-Kuz commented on TestProject.OpenSDK/XUnitLogger/XUnitLogger.cs
> +﻿// <copyright file="XUnitLogger.cs" company="TestProject">
Splitted into 2 commits

2021-07-28 20:56 UTC, mstrelex requested changes

2021-07-28 20:56 UTC, mstrelex commented on README.md
> +you will have to inherit from the `XUnitLogger` class and pass an `ITestOutputHelper` to it's constructor.
What if the user already inherits a class by his Test, can't we create an interface with a default implementation as we do in Java?

2021-07-29 07:03 UTC, Artem-Kuz commented on README.md
> +you will have to inherit from the `XUnitLogger` class and pass an `ITestOutputHelper` to it's constructor.
The user could inherit the XUnitLogger from his base class, default interface implementation is not support on the version of C# we are working according to Shay

2021-07-29 07:07 UTC, Artem-Kuz commented on TestProject.OpenSDK/XUnitLogger/XUnitLogger.cs
> +// Copyright 2020 TestProject (https://testproject.io)
Done

2021-07-29 08:48 UTC, s-glatshtein commented on README.md
> +you will have to inherit from the `XUnitLogger` class and pass an `ITestOutputHelper` to it's constructor.
@mstrelex this is the cleanest solution there's available with C# 6. If you want we can add a "dirty" solution as well that requires a method call

2021-08-02 12:59 UTC, mstrelex approved these changes

2021-08-02 12:59 UTC, merged