Fix linting warnings related to import statement order
testproject-io/csharp-opensdk pull request #95
Opened 2021-02-01 14:01 UTC by basdijkstra

This PR fixes a couple of warnings related to import statement order issued by .NETAnalyzer

2021-02-09 19:02 UTC, eldarkra requested changes

2021-02-09 19:02 UTC, eldarkra commented on TestProject.OpenSDK/Drivers/Android/AndroidDriver.cs
> +                // this.Report().DisableAutoTestReports(true);
Are all these should be commented out or here at all?

2021-02-10 07:44 UTC, basdijkstra commented on TestProject.OpenSDK/Drivers/Android/AndroidDriver.cs
> +                // this.Report().DisableAutoTestReports(true);
Hmm.. These files should not have been in here at all.

2021-02-10 07:54 UTC, basdijkstra commented
@eldarkra please review again, I've removed the files that did not belong to this PR.

2021-02-10 10:46 UTC, eldarkra approved these changes

2021-02-10 10:46 UTC, merged